# This rule is not used by the project hadesoperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the build.hades.tum.de.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hadesoperator
    app.kubernetes.io/managed-by: kustomize
  name: buildjob-editor-role
rules:
- apiGroups:
  - build.hades.tum.de
  resources:
  - buildjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.hades.tum.de
  resources:
  - buildjobs/status
  verbs:
  - get
