apiVersion: build.hades.tum.de/v1
kind: BuildJob
metadata:
  name: buildjob-sample-fail
  labels:
    app.kubernetes.io/name: hadesoperator
    app.kubernetes.io/managed-by: kustomize
spec:
  name: "Example Job (Failure)"
  priority: 3
  metadata:
    GLOBAL: "test"
  steps:
    - id: 1
      name: "Clone"
      image: "ghcr.io/ls1intum/hades/hades-clone-container:latest"
      metadata:
        REPOSITORY_DIR: "/shared"
        HADES_TEST_USERNAME: ""
        HADES_TEST_PASSWORD: ""
        HADES_TEST_URL: "https://github.com/Mtze/Artemis-Java-Test.git"
        HADES_TEST_PATH: "./example"
        HADES_TEST_ORDER: "1"
        HADES_ASSIGNMENT_USERNAME: ""
        HADES_ASSIGNMENT_PASSWORD: ""
        HADES_ASSIGNMENT_URL: "https://github.com/Mtze/Artemis-Java-Solution.git"
        HADES_ASSIGNMENT_PATH: "./example/assignment"
        HADES_ASSIGNMENT_ORDER: "2"
    - id: 2
      name: "Execute"
      image: "ls1tum/artemis-maven-template:java17-18"
      script: |
        set +e
        cd ./shared/example
        exit 1
  timeoutSeconds: 600
  maxRetries: 1
