apiVersion: build.hades.tum.de/v1
kind: BuildJob
metadata:
  name: buildjob-sample-report
  labels:
    app.kubernetes.io/name: hadesoperator
    app.kubernetes.io/managed-by: kustomize
spec:
  name: "Example Job"
  metadata:
    GLOBAL: "test"
  steps:
    - id: 1
      name: "Report Starting Time"
      image: "ghcr.io/ls1intum/hades-reporter/hades-reporter:latest"
      metadata:
        ENDPOINT: "https://ma-yu.aet.cit.tum.de/v1/start_time"
    - id: 2
      name: "Clone"
      image: "ghcr.io/ls1intum/hades/hades-clone-container:latest"
      metadata:
        REPOSITORY_DIR: "/shared"
        HADES_TEST_USERNAME: ""
        HADES_TEST_PASSWORD: ""
        HADES_TEST_URL: "https://github.com/Mtze/Artemis-Java-Test.git"
        HADES_TEST_PATH: "./example"
        HADES_TEST_ORDER: "1"
        HADES_ASSIGNMENT_USERNAME: ""
        HADES_ASSIGNMENT_PASSWORD: ""
        HADES_ASSIGNMENT_URL: "https://github.com/Mtze/Artemis-Java-Solution.git"
        HADES_ASSIGNMENT_PATH: "./example/assignment"
        HADES_ASSIGNMENT_ORDER: "2"
    - id: 3
      name: "Execute"
      image: "ls1tum/artemis-maven-template:java17-18"
      script: |
        set +e && \
        cd ./shared/example || exit 0 && \
        ./gradlew --status || exit 0 && \
        ./gradlew clean test || exit 0
    - id: 4
      name: "Report Results"
      image: "ghcr.io/ls1intum/hades/junit-result-parser:latest"
      metadata:
        API_ENDPOINT: "https://ma-yu.aet.cit.tum.de/v1/result"
        INGEST_DIR: "./shared/example"
        HADES_ASSIGNMENT_PATH: "./example/assignment"
  timeoutSeconds: 600
  maxRetries: 1
