apiVersion: apps/v1
kind: Deployment
metadata:
  name: "hades-scheduler"
  namespace: {{.Values.namespace.name}}
spec:
  replicas: {{ .Values.hadesScheduler.replicaCount }}
  selector:
    matchLabels:
      app: hades-scheduler-selector
  template:
    metadata:
      labels:
        app: hades-scheduler-selector
    spec:
      containers:
        - name: "hades-scheduler"
          image: "{{ .Values.hadesScheduler.image.repository }}:{{ .Values.hadesScheduler.image.tag }}"
          imagePullPolicy: {{ .Values.hadesScheduler.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.hadesScheduler.resources.limits.cpu | quote }}
              memory: {{ .Values.hadesScheduler.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.hadesScheduler.resources.requests.cpu | quote }}
              memory: {{ .Values.hadesScheduler.resources.requests.memory | quote }}
          ports:
            - containerPort: {{ .Values.hadesScheduler.service.targetPort }}
          env:
            - name: REDIS_ADDR
              value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
            - name: HADES_EXECUTOR
              value: "k8s"