apiVersion: v1
kind: Service
metadata:
  name: "hades-operator-service"
  labels:
    app.kubernetes.io/part-of: hades
    app.kubernetes.io/component: operator
spec:
  selector:
    app: hades-operator-selector
  ports:
    - name: http
      port: {{ .Values.hadesOperator.service.port }}
      targetPort: {{ .Values.hadesOperator.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
  type: {{ .Values.hadesOperator.service.type }}
