apiVersion: v1
kind: Service
metadata:
  name: "hades-log-manager-service"
spec:
  selector:
    app: hades-log-manager-selector
  ports:
    - port: {{ .Values.hadesLogManager.service.port }}
      targetPort: {{ .Values.hadesLogManager.service.targetPort }}
      protocol: TCP
  type: {{ .Values.hadesLogManager.service.type }}
