apiVersion: v1
kind: Service
metadata:
  name: "hades-api-service"
  labels:
    app.kubernetes.io/part-of: hades
    app.kubernetes.io/component: api
spec:
  selector:
    app: hades-api-selector
  ports:
    - name: http
      port: {{ .Values.hadesApi.service.port }}
      targetPort: {{ .Values.hadesApi.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
  type: {{ .Values.hadesApi.service.type }}
