apiVersion: v1
kind: Service
metadata:
  name: "hades-log-manager-service"
  labels:
    app.kubernetes.io/part-of: hades
    app.kubernetes.io/component: log-manager
spec:
  selector:
    app: hades-log-manager-selector
  ports:
    - name: http
      port: {{ .Values.hadesLogManager.service.port }}
      targetPort: {{ .Values.hadesLogManager.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
  type: {{ .Values.hadesLogManager.service.type }}
