apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hades-scheduler-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.name}}
  apiGroup: rbac.authorization.k8s.io
