{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "hades-ingress"
  namespace: "{{ .Values.namespace.name }}"
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{ toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # Hades API
          - path: /build
            pathType: Prefix
            backend:
              service:
                name: "hades-api-service"
                port:
                  number: {{ .Values.hadesApi.service.port }}

          # Hades Scheduler
          - path: /scheduler
            pathType: Prefix
            backend:
              service:
                name: "hades-scheduler-service"
                port:
                  number: {{ .Values.hadesScheduler.service.port }}
{{- end }}