apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hades-scheduler-rolebinding
  namespace: {{ .Values.namespace.name }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.role.name}}
  apiGroup: rbac.authorization.k8s.io
