# This rule is not used by the project hadesoperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to build.hades.tum.de resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hadesoperator
    app.kubernetes.io/managed-by: kustomize
  name: buildjob-viewer-role
rules:
- apiGroups:
  - build.hades.tum.de
  resources:
  - buildjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - build.hades.tum.de
  resources:
  - buildjobs/status
  verbs:
  - get
