---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - build.hades.tum.de
  resources:
  - buildjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.hades.tum.de
  resources:
  - buildjobs/finalizers
  verbs:
  - update
- apiGroups:
  - build.hades.tum.de
  resources:
  - buildjobs/status
  verbs:
  - get
  - patch
  - update
