name: Build Docker Images

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - main
      - release/*
  push:
    branches:
      - main
      - release/*
  release:
    types:
      - created

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./HadesAPI/Dockerfile
            image: ls1intum/hades/hades-api
          - dockerfile: ./HadesScheduler/Dockerfile
            image: ls1intum/hades/hades-scheduler
          - dockerfile: ./HadesScheduler/HadesOperator/Dockerfile
            image: ls1intum/hades/hades-operator
    uses: ls1intum/.github/.hades/workflows/build-and-push-docker-image.yml@v1.1.1
    with:
      image-name: ${{ matrix.image }}
      docker-file: ${{ matrix.dockerfile }}
